#!/bin/bash

THIS_SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"

do_init() {
    echo "${USER} ALL=(ALL)  NOPASSWD: ALL" >> /etc/sudoers
    echo "export PS1='(etbox - $(date +%s)) [\\u@\\h \\W]\\\$ '"  >> /etc/profile

    exec sudo -E -u "${USER}" /usr/bin/bash -l -- "$@"
}

if [ "${THIS_SCRIPT}" = "/usr/bin/entrypoint" ]; then
    do_init "$@"
    exit
fi


if [ ! -d "$HOME/.cache/dnf" ]; then
    mkdir -v "${HOME}/.cache/dnf"
fi

if rpm -ql xorg-x11-drv-nvidia >/dev/null; then
	NVIDIA_DRIVERS="$(rpm -ql xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs | grep -v ".build-id" | xargs -I{} bash -c "test -e {} && echo '-v {}:{} '")"
fi


podman run \
    --rm -it \
    --privileged \
    --userns keep-id \
    --systemd always \
    --gpus all \
    --volume ${THIS_SCRIPT}:/usr/bin/entrypoint \
    --volume /:/run/host:ro \
    --volume /run/dbus:/run/dbus \
    --volume /run/udev:/run/udev \
    --volume /run/libvirt:/run/libvirt \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
    --volume /run/systemd/journal:/run/systemd/journal \
    --volume "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}" \
    --volume "$HOME/.cache/dnf:/var/cache/dnf" \
    --volume "$HOME:$HOME:rslave" \
    --volume "$PWD:$PWD" \
    --volume /etc/dnf/dnf.conf:/etc/dnf/dnf.conf:ro \
    --volume /etc/pki/rpm-gpg:/etc/pki/rpm-gpg:ro \
    --volume /etc/yum.repos.d:/etc/yum.repos.d:ro \
    --volume /etc/host.conf:/etc/host.conf:ro \
    --volume /etc/localtime:/etc/localtime:ro \
    --volume /etc/machine-id:/etc/machine-id:ro \
    --device /dev/snd \
    ${NVIDIA_DRIVERS} \
    -w "$PWD" \
    --pids-limit -1 \
    --security-opt label=disable \
    --ipc host \
    --network host \
    --user root \
    -e SSH_AUTH_SOCK \
    -e GDK_SCALE \
    -e GDK_DPI_SCALE \
    -e QT_AUTO_SCREEN_SCALE_FACTOR \
    -e QT_SCREEN_SCALE_FACTORS \
    -e GTK_RC_FILES \
    -e GTK2_RC_FILES \
    -e DISPLAY \
    -e DBUS_SESSION_BUS_ADDRESS \
    -e XDG_RUNTIME_DIR \
    -e XCURSOR_SIZE \
    -e USER \
    -e SHELL \
    -e TERM \
    -e ETBOX_NVIDIA \
    -e ETBOX_RPMFUSION \
    --entrypoint /usr/bin/entrypoint \
    "fedora:$(rpm --eval %fedora)" "$@"
